### ISSUE TITLE
can you share whole project?

### ISSUE THREAD

**Issue by tirthsutaria** [krilor/gdoc2json#1]
Hey,
I am Tirth. I am the one who commented on your YouTube video.  I am trying to run your code but it's giving me error. I think to do exact same thing which you are doing in video this one file (gdoc2json.gs) is not enough but I'm not sure what to do? can you please share your project as a whole or tell me what to do?
Thanks.

**Comment by krilor** [comment]
Hi Tirth
I've uploaded the full Apps Script project here:
https://github.com/krilor/gdoc2json/tree/whole-project

Read up on script projects to understand more.
https://developers.google.com/apps-script/guides/projects

Let me know if you have any issues.

**Comment by tirthsutaria** [comment]
Hi, 
I've created a project and copied all the files but it's still giving me the same error. What I've understood is i need to run gdoc2json function. But it keeps saying  "TypeError: cannot call method "getBody" of undefined"
<img width="960" alt="error" src="https://user-images.githubusercontent.com/33231510/32672829-99d3c206-c61a-11e7-9f3a-0eb8530c0de5.png">

**Comment by krilor** [comment]
@tirthsutaria Sorry for not responding sooner

 Have you tried publishing it as a web app?
https://developers.google.com/apps-script/guides/web#deploying_a_script_as_a_web_app

**Comment by tirthsutaria** [comment]
@krilor  No problem. I solved the issue. Thanks for all the help.
